# Generated by Django 4.0.1 on 2022-01-29 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_alter_driver_max_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_sharers', models.PositiveIntegerField(default=1)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_owners', models.PositiveIntegerField(default=1)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'open'), ('confirm', 'confirm'), ('complete', 'complete')], default='open', max_length=10)),
                ('arrival_time', models.DateTimeField()),
                ('allow_share', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=10)),
                ('special_request', models.CharField(blank=True, max_length=200)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
