# Generated by Django 4.0.1 on 2022-01-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('num_owners', models.PositiveIntegerField(default=1)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(default='open', max_length=10)),
                ('arrival_time', models.DateTimeField()),
                ('vehicle_type', models.CharField(blank=True, max_length=10)),
                ('share', models.BooleanField(default=False)),
                ('special_request', models.CharField(blank=True, max_length=200)),
                ('driver', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=20)),
                ('vehicle_volume', models.PositiveIntegerField(default=0)),
                ('special_vehicle_info', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_sharers', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
