# Generated by Django 4.0.1 on 2022-01-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='share',
            new_name='allow_share',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='license',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='special_vehicle_info',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='vehicle_volume',
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.TimeField(),
        ),
    ]
