# Generated by Django 4.0.1 on 2022-01-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('confirm', 'confirm'), ('complete', 'complete'), ('open', 'open')], default='open', max_length=10),
        ),
    ]
