# Generated by Django 4.0.1 on 2022-01-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('open', 'open'), ('confirm', 'confirm')], default='open', max_length=10),
        ),
    ]
