# Generated by Django 4.0.1 on 2022-01-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_driver_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='max_volume',
            field=models.PositiveIntegerField(),
        ),
    ]
